### ISSUE TITLE
toxic build fails: unknown type name 'timer_t' OSX 10.7.5

### ISSUE THREAD

**Issue by lallen** [Tox/homebrew-tox#20]
Building toxic ($brew install --HEAD toxic) fails, unknown type timer_t. Any idea what I'm missing?

https://gist.github.com/27f060be78778e7afe29

/private/tmp/toxic-phu2Kv/src/term_mplex.c:272:5: error: unknown type name 'timer_t'; did you mean 'time_t'?
    timer_t timer_id;
    ^~~~~~~
    time_t
/usr/include/time.h:87:26: note: 'time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
/private/tmp/toxic-phu2Kv/src/term_mplex.c:273:23: error: variable has incomplete type 'struct itimerspec'
    struct itimerspec its;
                      ^
/private/tmp/toxic-phu2Kv/src/term_mplex.c:273:12: note: forward declaration of 'struct itimerspec'
    struct itimerspec its;
           ^
/private/tmp/toxic-phu2Kv/src/term_mplex.c:285:23: error: use of undeclared identifier 'CLOCK_REALTIME'
    if (timer_create (CLOCK_REALTIME, &sev, &timer_id) == -1)
                      ^
3 errors generated.

**Comment by dubslow** [comment]
@JFreegman ...?

**Comment by JFreegman** [comment]
@lallen This should be resolved now. Let me know if there's still an issue please.

**Comment by lallen** [comment]
Working now, thanks! :+1:
