### ISSUE TITLE
Make fail

### ISSUE THREAD

**Issue by fenque** [Tox/homebrew-tox#26]
```
==> make
    static io_service_t service = NULL;
                        ~~~~~~~   ^~~~
                                  0
2 warnings and 6 errors generated.
make: *** [timer_osx.o] Error 1
```

**Comment by stal888** [comment]
What are you making?

**Comment by fenque** [comment]
Sorry, forgot to write it, i making qtox.

**Comment by urras** [comment]
@stal888 This is an outdated core thing, right?

**Comment by stal888** [comment]
@urras No, it's a qtox error.

@fenque I don't know enough about qTox's build process to support it. Maybe file a bug on the main repo.

**Comment by tux3** [comment]
@fenque 
It says "2 warnings and 6 errors generated.", can you show all of the output?

**Comment by fenque** [comment]
@tux3 https://gist.github.com/fenque/f74a1f0110809b7c7720

**Comment by tux3** [comment]
@fenque I fixed the one warning that was in our code (NULL -> 0), and remove the unnecessary QDebug header that your compiler seems to hate, but in the end the problem isn't in qTox's code, so this isn't something I can fix.
Your dev environment or the build script seems to be broken.
