### ISSUE TITLE
Build fail -- toxic

### ISSUE THREAD

**Issue by loru** [Tox/homebrew-tox#41]
Hello,

toxic cannot build on OSX, how do I fix this? I cannot compile it.
The log:

MacBook-Pro% brew install toxic --HEAD
==> Installing toxic from tox/tox
==> Cloning git://github.com/Tox/toxic
Updating /Users/user/Library/Caches/Homebrew/toxic--git
==> Checking out branch master
Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/tox/homebrew-tox/Formula/toxic.rb:22:in `hacks'
Please report this to the tox/tox tap!

==> make PREFIX='/usr/local/Cellar/toxic/HEAD-b14d983' DISABLE_DESKTOP_NOTIFY=YES DISABLE_X11=YES
Last 15 lines from /Users/user/Library/Logs/Homebrew/toxic/01.make:
  CC    toxic_strings.o
  CC    windows.o
  CC    osx_video.o
  CC    audio_call.o
  CC    audio_device.o
/private/tmp/toxic-20180220-50143-14emevk/src/audio_call.c:865:18: error: use of undeclared identifier 'TOXAV_ERR_BIT_RATE_SET_INVALID_AUDIO_BIT_RATE'; did you mean 'TOXAV_ERR_BIT_RATE_SET_INVALID_BIT_RATE'?
            case TOXAV_ERR_BIT_RATE_SET_INVALID_AUDIO_BIT_RATE:
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 TOXAV_ERR_BIT_RATE_SET_INVALID_BIT_RATE
/usr/local/Cellar/libtoxcore/HEAD-95c03e0/include/tox/toxav.h:499:5: note: 'TOXAV_ERR_BIT_RATE_SET_INVALID_BIT_RATE' declared here
    TOXAV_ERR_BIT_RATE_SET_INVALID_BIT_RATE,
    ^
1 error generated.
make: *** [/private/tmp/toxic-20180220-50143-14emevk/build/audio_call.o] Error 1
make: *** Waiting for unfinished jobs....

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/tox/homebrew-tox/issues

Any idea how I could fix it?

**Comment by publicarray** [comment]
#42 should fix this.

**Comment by robinlinden** [comment]
Fixed in #42.
